---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    attributes:
      php:
        # FIXME
        ext_conf_dir: "/etc/php5/mods-available"

suites:
  - name: default
    run_list:
      - recipe[laravel::default]
    attributes:
      laravel:
        project_name: "test_app"
        github_oauth: "FIXME"
      mysql:
        server_root_password: ""
        server_debian_password: ""
        server_repl_password: ""
